// Regenerated before every build/serve (see package.json "pre*" scripts) -
// keep this file's output format in sync with src/app/version.ts's type.
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const pkg = require('../package.json');

function run(cmd, fallback) {
  try {
    return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim();
  } catch {
    return fallback;
  }
}

const commit = run('git rev-parse --short HEAD', 'unknown');
const dirty = run('git status --porcelain', '') !== '' ? '-dirty' : '';

const version = {
  version: pkg.version,
  commit: `${commit}${dirty}`,
  buildDate: new Date().toISOString(),
};

const outPath = path.join(__dirname, '..', 'src', 'app', 'version.ts');
const contents = `// Auto-generated by scripts/generate-version.js - do not edit by hand.
export const VERSION = ${JSON.stringify(version, null, 2)};
`;

fs.writeFileSync(outPath, contents);
console.log(`Wrote ${outPath}:`, version);
